package generate

import (
	"bytes"
	"fmt"
	"go/format"
	"go/token"
	"slices"
	"strconv"
	"strings"
	"text/template"
	"unicode"

	"github.com/aiveto/veto/catalog"
)

const (
	sdkTmpl = `// Code generated by veto generate. DO NOT EDIT.

package sdk

import (
	"context"
	"net/http"

	"github.com/aiveto/veto/catalog"
	"github.com/aiveto/veto/execute"
	"github.com/aiveto/veto/policy"
	"github.com/aiveto/veto/runtime"
)

// Client is the Go client for one contract. Calls go through the invoke runtime.
type Client struct {
	Calls runtime.Runtime
}

// New builds a client whose calls pass the policy gate.
func New(baseURL string, httpClient *http.Client) (*Client, error) {
	cat := &catalog.Catalog{
		Operations: []catalog.Operation{
{{- range .Ops}}
			{
				ID: {{quote .ID}},
				Method: {{quote .Method}},
				PathTemplate: {{quote .Path}},
				Description: {{quote .Description}},
				Group: {{quote .Group}},
				Kind: {{.KindLit}},
				Tags: {{list .Tags}},
				SideEffect: {{.SideConst}},
				RequiresConfirmation: {{.Confirm}},
				Permissions: {{list .Permissions}},
				Idempotency: {{quote .Idempotency}},
				Retry: {{quote .Retry}},
				Exposure: {{.ExposureLit}},
				BaseURL: {{quote .BaseURL}},
				Auth: {{.AuthLit}},
				Requirements: {{.ReqLit}},
				Params: []catalog.Param{
{{- range .Params}}
					{Name: {{quote .Name}}, In: {{quote .In}}, Required: {{.Required}}, Description: {{quote .Description}}, Schema: {{quote .Schema}}, MediaType: {{quote .MediaType}}, Default: {{quote .Default}}, Style: {{quote .Style}}, Explode: {{.Explode}}},
{{- end}}
				},
			},
{{- end}}
		},
	}
	cat.Finalize()
	return &Client{Calls: runtime.Runtime{
		Catalog: cat,
		Policy:  policy.Builtin{},
		State:   policy.NewState(),
		Exec:    execute.Client{BaseURL: baseURL, HTTP: httpClient},
	}}, nil
}

{{range .Ops}}
func (c *Client) {{.GoName}}(ctx context.Context{{range .Params}}, {{.GoName}} string{{end}}, approvalID string) (runtime.Result, error) {
	return c.Calls.Invoke(ctx, runtime.Request{
		Operation: {{quote .ID}},
		Arguments: map[string]any{
{{- range .Params}}
			{{quote .Name}}: {{.GoName}},
{{- end}}
		},
		Approval: approvalID,
	})
}
{{end}}
`

	cliTmpl = `// Code generated by veto generate. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"{{.Module}}/sdk"
)

type helpDoc struct {
	Command      string    ` + "`json:\"command\"`" + `
	OperationID  string    ` + "`json:\"operation\"`" + `
	Method       string    ` + "`json:\"method\"`" + `
	Description  string    ` + "`json:\"description\"`" + `
	Params       []helpArg ` + "`json:\"params\"`" + `
	SideEffect   string    ` + "`json:\"side_effect\"`" + `
	Confirmation bool      ` + "`json:\"confirmation\"`" + `
	Permissions  []string  ` + "`json:\"permissions\"`" + `
	Server       string    ` + "`json:\"server\"`" + `
	Errors       []string  ` + "`json:\"errors\"`" + `
}

type helpArg struct {
	Name        string ` + "`json:\"name\"`" + `
	In          string ` + "`json:\"in\"`" + `
	Type        string ` + "`json:\"type\"`" + `
	Required    bool   ` + "`json:\"required\"`" + `
	Description string ` + "`json:\"description\"`" + `
}

func main() {
	if len(os.Args) < 2 {
		usage()
		os.Exit(2)
	}
	switch os.Args[1] {
{{- range .Ops}}
	case {{quote .Command}}:
		run{{.GoName}}(os.Args[2:])
{{- end}}
	default:
		usage()
		os.Exit(2)
	}
}

func usage() {
	fmt.Fprintln(os.Stderr, "usage: <command> [--help-json]")
}

func client() *sdk.Client {
	c, err := sdk.New(os.Getenv("VETO_BASE_URL"), nil)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	return c
}

func finish(status string, httpStatus int, err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if status != "ok" {
		fmt.Fprintln(os.Stderr, status)
		os.Exit(1)
	}
	fmt.Println(httpStatus)
}

{{range .Ops}}
func run{{.GoName}}(args []string) {
	fs := flag.NewFlagSet({{quote .Command}}, flag.ExitOnError)
	helpJSON := fs.Bool("help-json", false, "print command metadata as JSON")
{{- if .Confirm}}
	confirm := fs.Bool("confirm", false, "confirm this destructive call")
{{- end}}
{{- range .Params}}
	{{.GoName}} := fs.String({{quote .Flag}}, "", {{quote .FlagHelp}})
{{- end}}
	_ = fs.Parse(args)
	if *helpJSON {
		enc := json.NewEncoder(os.Stdout)
		if err := enc.Encode(helpDoc{
			Command: {{quote .Command}},
			OperationID: {{quote .ID}},
			Method: {{quote .Method}},
			Description: {{quote .Description}},
			SideEffect: {{quote .SideEffect}},
			Confirmation: {{.Confirm}},
			Permissions: {{list .Permissions}},
			Server: {{quote .BaseURL}},
			Errors: []string{},
			Params: []helpArg{
{{- range .Params}}
				{Name: {{quote .Flag}}, In: {{quote .In}}, Type: "string", Required: {{.Required}}, Description: {{quote .FlagHelp}}},
{{- end}}
			},
		}); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	c := client()
	call, err := c.{{.GoName}}(context.Background(){{range .Params}}, *{{.GoName}}{{end}}, "")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
{{- if .Confirm}}
	if call.Status == "confirmation_required" {
		if !*confirm {
			fmt.Fprintln(os.Stderr, "confirmation required")
			os.Exit(2)
		}
		approved, aerr := c.Calls.State.Approve(call.ApprovalID)
		if aerr != nil {
			fmt.Fprintln(os.Stderr, aerr)
			os.Exit(1)
		}
		call, err = c.{{.GoName}}(context.Background(){{range .Params}}, *{{.GoName}}{{end}}, approved)
	}
{{- end}}
	finish(call.Status, call.HTTPStatus, err)
}
{{end}}
`

	dispatchTmpl = `// Code generated by veto generate. DO NOT EDIT.

package dispatch

import (
	"context"
	"fmt"

	"github.com/aiveto/veto/runtime"
	"{{.Module}}/sdk"
)

// Call sends one operation id through the Go client and the policy gate.
func Call(ctx context.Context, c *sdk.Client, operationID string, params map[string]string, approvalID string) (runtime.Result, error) {
	if c == nil || c.Calls.Catalog == nil {
		return runtime.Result{}, fmt.Errorf("nil sdk client")
	}
	switch operationID {
{{- range .Ops}}
	case {{quote .ID}}:
		return c.{{.GoName}}(ctx{{range .Params}}, params[{{quote .Name}}]{{end}}, approvalID)
{{- end}}
	default:
		return runtime.Result{}, fmt.Errorf("unknown operation %q", operationID)
	}
}
`
)

type (
	Files struct {
		SDK []byte
		CLI []byte
		MCP []byte
	}

	opView struct {
		ID          string
		GoName      string
		Command     string
		Method      string
		Path        string
		Description string
		Group       string
		KindLit     string
		Tags        []string
		SideEffect  string
		SideConst   string
		Confirm     bool
		Permissions []string
		Idempotency string
		Retry       string
		ExposureLit string
		BaseURL     string
		AuthLit     string
		ReqLit      string
		Params      []paramView
	}

	paramView struct {
		Name        string
		Flag        string
		FlagHelp    string
		GoName      string
		In          string
		Required    bool
		Description string
		Schema      string
		MediaType   string
		Default     string
		Style       string
		Explode     bool
	}
)

func Render(module string, cat *catalog.Catalog) (Files, error) {
	if err := validModule(module); err != nil {
		return Files{}, err
	}
	views := views(cat)
	sdk, err := render("sdk", sdkTmpl, map[string]any{"Ops": views})
	if err != nil {
		return Files{}, err
	}
	cli, err := render("cli", cliTmpl, map[string]any{"Module": module, "Ops": views})
	if err != nil {
		return Files{}, err
	}
	mcp, err := render("dispatch", dispatchTmpl, map[string]any{"Module": module, "Ops": views})
	if err != nil {
		return Files{}, err
	}
	return Files{SDK: sdk, CLI: cli, MCP: mcp}, nil
}

func views(cat *catalog.Catalog) []opView {
	ops := append([]catalog.Operation(nil), cat.Operations...)
	slices.SortFunc(ops, func(a, b catalog.Operation) int { return strings.Compare(a.ID, b.ID) })
	usedCmd := map[string]int{}
	usedGo := map[string]int{"New": 1, "Calls": 1}
	out := make([]opView, 0, len(ops))
	for _, op := range ops {
		goName := unique(usedGo, goName(op.ID))
		cmd := unique(usedCmd, commandName(op.ID))
		params := make([]paramView, 0, len(op.Params))
		usedArg := reservedArgs()
		usedFlag := reservedFlags(op.RequiresConfirmation)
		for _, p := range op.Params {
			flag := uniqueFlag(usedFlag, cliFlag(p.Name))
			params = append(params, paramView{
				Name:        p.Name,
				Flag:        flag,
				FlagHelp:    flagHelp(p.Name, flag, p.Description),
				GoName:      unique(usedArg, argName(p.Name)),
				In:          p.In,
				Required:    p.Required || p.In == "path",
				Description: p.Description,
				Schema:      p.Schema,
				MediaType:   p.MediaType,
				Default:     p.Default,
				Style:       p.Style,
				Explode:     p.Explode,
			})
		}
		out = append(out, opView{
			ID:          op.ID,
			GoName:      goName,
			Command:     cmd,
			Method:      op.Method,
			Path:        op.PathTemplate,
			Description: op.Description,
			Group:       op.Group,
			KindLit:     kindLit(op.Kind),
			Tags:        op.Tags,
			SideEffect:  string(op.SideEffect),
			SideConst:   sideConst(op.SideEffect),
			Confirm:     op.RequiresConfirmation,
			Permissions: op.Permissions,
			Idempotency: op.Idempotency,
			Retry:       op.Retry,
			ExposureLit: exposureLit(op.Exposure),
			BaseURL:     op.BaseURL,
			AuthLit:     authSliceLit(op.Auth),
			ReqLit:      reqLit(op.Requirements),
			Params:      params,
		})
	}
	return out
}

func reservedFlags(confirm bool) map[string]int {
	used := map[string]int{"help-json": 1}
	if confirm {
		used["confirm"] = 1
	}
	return used
}

func cliFlag(name string) string {
	if name == "" || strings.HasPrefix(name, "-") || strings.ContainsAny(name, "= \t") {
		return "arg"
	}
	return name
}

func flagHelp(name, flag, desc string) string {
	if flag == name {
		return desc
	}
	note := "parameter " + name
	if desc == "" {
		return note
	}
	return desc + " (" + note + ")"
}

func uniqueFlag(seen map[string]int, name string) string {
	if seen[name] == 0 {
		seen[name] = 1
		return name
	}
	for i := 2; ; i++ {
		next := name + "-" + strconv.Itoa(i)
		if seen[next] == 0 {
			seen[next] = 1
			return next
		}
	}
}

func reservedArgs() map[string]int {
	names := []string{
		"ctx", "approvalID", "c", "args", "fs", "helpJSON", "confirm",
		"call", "err", "approved", "aerr", "enc", "os", "fmt", "json",
		"flag", "context", "sdk", "runtime", "http", "catalog", "execute",
		"policy", "client", "finish", "usage", "status", "httpStatus",
	}
	out := make(map[string]int, len(names))
	for _, name := range names {
		out[name] = 1
	}
	return out
}

func validModule(path string) error {
	if strings.ContainsAny(path, " \t\r\n\"'`\\;") || strings.Contains(path, "..") {
		return fmt.Errorf("module path %q is not valid", path)
	}
	first, rest, ok := strings.Cut(path, "/")
	if !ok || first == "" || rest == "" || !strings.Contains(first, ".") {
		return fmt.Errorf("module path %q is not valid", path)
	}
	for part := range strings.SplitSeq(path, "/") {
		if part == "" || part == "." || part == ".." {
			return fmt.Errorf("module path %q is not valid", path)
		}
	}
	return nil
}

func unique(seen map[string]int, name string) string {
	if seen[name] == 0 {
		seen[name] = 1
		return name
	}
	for i := 2; ; i++ {
		next := fmt.Sprintf("%s%d", name, i)
		if seen[next] == 0 {
			seen[next] = 1
			return next
		}
	}
}

func goName(id string) string {
	parts := strings.FieldsFunc(id, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	var b strings.Builder
	for _, p := range parts {
		b.WriteString(export(p))
	}
	s := b.String()
	if s == "" || unicode.IsDigit(rune(s[0])) {
		s = "Op" + s
	}
	return s
}

func commandName(id string) string {
	if i := strings.LastIndex(id, "."); i >= 0 && i < len(id)-1 {
		id = id[i+1:]
	}
	return strings.ToLower(id)
}

func argName(name string) string {
	parts := strings.FieldsFunc(name, func(r rune) bool {
		return !unicode.IsLetter(r) && !unicode.IsDigit(r)
	})
	if len(parts) == 0 {
		return "arg"
	}
	s := strings.ToLower(parts[0])
	var rest strings.Builder
	for _, p := range parts[1:] {
		rest.WriteString(export(p))
	}
	s += rest.String()
	if !token.IsIdentifier(s) || token.IsKeyword(s) {
		s = "arg" + export(s)
	}
	return s
}

func export(s string) string {
	if s == "" {
		return ""
	}
	r := []rune(s)
	r[0] = unicode.ToUpper(r[0])
	return string(r)
}

func kindLit(k catalog.Kind) string {
	switch k {
	case catalog.KindRead:
		return "catalog.KindRead"
	case catalog.KindCreate:
		return "catalog.KindCreate"
	case catalog.KindUpdate:
		return "catalog.KindUpdate"
	case catalog.KindDelete:
		return "catalog.KindDelete"
	case catalog.KindAction:
		return "catalog.KindAction"
	default:
		return "catalog.Kind(" + strconv.Quote(string(k)) + ")"
	}
}

func exposureLit(s string) string {
	switch s {
	case catalog.ExposureDirect:
		return "catalog.ExposureDirect"
	case catalog.ExposureGrouped:
		return "catalog.ExposureGrouped"
	case catalog.ExposureDiscovery:
		return "catalog.ExposureDiscovery"
	default:
		return strconv.Quote(s)
	}
}

func authSliceLit(list []catalog.Auth) string {
	if len(list) == 0 {
		return "nil"
	}
	parts := make([]string, len(list))
	for i, a := range list {
		parts[i] = authLit(a)
	}
	return "[]catalog.Auth{" + strings.Join(parts, ", ") + "}"
}

func reqLit(groups [][]catalog.Auth) string {
	if len(groups) == 0 {
		return "nil"
	}
	parts := make([]string, len(groups))
	for i, group := range groups {
		parts[i] = authSliceLit(group)
	}
	return "[][]catalog.Auth{" + strings.Join(parts, ", ") + "}"
}

func authLit(a catalog.Auth) string {
	return fmt.Sprintf("catalog.Auth{Name: %s, Header: %s, Query: %s, Kind: %s, Scopes: %s, UserHeader: %s, Type: %s, Scheme: %s}",
		strconv.Quote(a.Name),
		strconv.Quote(a.Header),
		strconv.Quote(a.Query),
		strconv.Quote(a.Kind),
		quoteList(a.Scopes),
		strconv.Quote(a.UserHeader),
		strconv.Quote(a.Type),
		strconv.Quote(a.Scheme),
	)
}

func sideConst(s catalog.SideEffect) string {
	switch s {
	case catalog.SideEffectNone:
		return "catalog.SideEffectNone"
	case catalog.SideEffectWrite:
		return "catalog.SideEffectWrite"
	case catalog.SideEffectDestructive:
		return "catalog.SideEffectDestructive"
	default:
		return "catalog.SideEffect(" + strconv.Quote(string(s)) + ")"
	}
}

func quoteList(ss []string) string {
	if len(ss) == 0 {
		return "[]string{}"
	}
	parts := make([]string, len(ss))
	for i, s := range ss {
		parts[i] = strconv.Quote(s)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

func render(name, src string, data any) ([]byte, error) {
	tmpl, err := template.New(name).Funcs(template.FuncMap{
		"quote": strconv.Quote,
		"list":  quoteList,
	}).Parse(src)
	if err != nil {
		return nil, fmt.Errorf("parse %s template: %w", name, err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return nil, fmt.Errorf("render %s: %w", name, err)
	}
	out, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format %s: %w\n%s", name, err, buf.String())
	}
	return out, nil
}
